export const EMPTY = "EMPTY"
export const LOGIN = "LOGIN"
export const REGISTER = "REGISTER"
export const FORGOT_PASSWORD = "FORGOT_PASSWORD"
export const NEW_PASSWORD = "NEW_PASSWORD"
export const OTP_PAGE = "OTP_PAGE"