export const MY_RDP_LIST_DATA_DUMMY = [
  {
    title: "Pc kuwat RTX 3080 Cocok untuk render",
    ID: "1234567890",
    date: "12-02-2022",
    img: {
      src: "https://www.shutterstock.com/image-photo/gaming-pc-rgb-led-lights-600w-1621672105.jpg",
      alt: "img-1",
    },
    cpu: {
      title: "Intel I5 6600K",
      core: 4,
      thread: 4,
      clockSpeed: 3.9,
    },
    graphical: {
      title: "Nvidia RTX 3080",
      cudeCore: 10240,
      clockSpeed: 3.9,
      memory: 12,
      memoryUnit: "GB",
      memoryType: "GDDR6X",
    },
    storageList: [
      {
        title: "Main Disk C",
        storageSpace: "512",
        storageSpaceUnit: "GB",
        transferSpeed: "3200",
        transferSpeedUnit: "MB/s",
        isNVME: true,
        installedOs: true,
      },
      {
        title: "Storage Disk D",
        storageSpace: "1024",
        storageSpaceUnit: "GB",
        transferSpeed: "1600",
        transferSpeedUnit: "MB/s",
        isNVME: false,
      },
      {
        title: "Storage Disk E",
        storageSpace: "1024",
        storageSpaceUnit: "GB",
        transferSpeed: "1600",
        transferSpeedUnit: "MB/s",
        isNVME: false,
      },
    ],
    rentDetail: {
      duration: 5,
      durationUnit: "Hours",
      endAt: "13-2-2022 00:00:00AM",
      price: 5.99,
      priceUnit: "$ / Hour",
      status: "ACTIVE",
    },
  },
  {
    title: "Pc kuwat RTX 3080 Cocok untuk render",
    ID: "1234567890",
    date: "12-02-2022",
    img: {
      src: "https://www.shutterstock.com/image-photo/gaming-pc-rgb-led-lights-600w-1621672105.jpg",
      alt: "img-1",
    },
    cpu: {
      title: "Intel I5 6600K",
      core: 4,
      thread: 4,
      clockSpeed: 3.9,
    },
    graphical: {
      title: "Nvidia RTX 3080",
      cudeCore: 10240,
      clockSpeed: 3.9,
      memory: 12,
      memoryUnit: "GB",
      memoryType: "GDDR6X",
    },
    storageList: [
      {
        title: "Main Disk C",
        storageSpace: "512",
        storageSpaceUnit: "GB",
        transferSpeed: "3200",
        transferSpeedUnit: "MB/s",
        isNVME: true,
        installedOs: true,
      },
      {
        title: "Storage Disk D",
        storageSpace: "1024",
        storageSpaceUnit: "GB",
        transferSpeed: "1600",
        transferSpeedUnit: "MB/s",
        isNVME: false,
      },
      {
        title: "Storage Disk E",
        storageSpace: "1024",
        storageSpaceUnit: "GB",
        transferSpeed: "1600",
        transferSpeedUnit: "MB/s",
        isNVME: false,
      },
    ],
    rentDetail: {
      duration: 24,
      durationUnit: "Hours",
      endAt: "13-2-2022 00:00:00AM",
      price: 5,
      priceUnit: "$ / Hour",
      status: "ACTIVE",
    },
  },
  {
    title: "Pc kuwat RTX 3080 Cocok untuk render",
    ID: "1234567890",
    date: "12-02-2022",
    img: {
      src: "https://www.shutterstock.com/image-photo/gaming-pc-rgb-led-lights-600w-1621672105.jpg",
      alt: "img-1",
    },
    cpu: {
      title: "Intel I5 6600K",
      core: 4,
      thread: 4,
      clockSpeed: 3.9,
    },
    graphical: {
      title: "Nvidia RTX 3080",
      cudeCore: 10240,
      clockSpeed: 3.9,
      memory: 12,
      memoryUnit: "GB",
      memoryType: "GDDR6X",
    },
    storageList: [
      {
        title: "Main Disk C",
        storageSpace: "512",
        storageSpaceUnit: "GB",
        transferSpeed: "3200",
        transferSpeedUnit: "MB/s",
        isNVME: true,
        installedOs: true,
      },
      {
        title: "Storage Disk D",
        storageSpace: "1024",
        storageSpaceUnit: "GB",
        transferSpeed: "1600",
        transferSpeedUnit: "MB/s",
        isNVME: false,
      },
      {
        title: "Storage Disk E",
        storageSpace: "1024",
        storageSpaceUnit: "GB",
        transferSpeed: "1600",
        transferSpeedUnit: "MB/s",
        isNVME: false,
      },
    ],
    rentDetail: {
      duration: 24,
      durationUnit: "Hours",
      endAt: "13-2-2022 00:00:00AM",
      price: 5,
      priceUnit: "$ / Hour",
      status: "ACTIVE",
    },
  },
  {
    title: "Pc kuwat RTX 3080 Cocok untuk render",
    ID: "1234567890",
    date: "12-02-2022",
    img: {
      src: "https://www.shutterstock.com/image-photo/gaming-pc-rgb-led-lights-600w-1621672105.jpg",
      alt: "img-1",
    },
    cpu: {
      title: "Intel I5 6600K",
      core: 4,
      thread: 4,
      clockSpeed: 3.9,
    },
    graphical: {
      title: "Nvidia RTX 3080",
      cudeCore: 10240,
      clockSpeed: 3.9,
      memory: 12,
      memoryUnit: "GB",
      memoryType: "GDDR6X",
    },
    storageList: [
      {
        title: "Main Disk C",
        storageSpace: "512",
        storageSpaceUnit: "GB",
        transferSpeed: "3200",
        transferSpeedUnit: "MB/s",
        isNVME: true,
        installedOs: true,
      },
      {
        title: "Storage Disk D",
        storageSpace: "1024",
        storageSpaceUnit: "GB",
        transferSpeed: "1600",
        transferSpeedUnit: "MB/s",
        isNVME: false,
      },
      {
        title: "Storage Disk E",
        storageSpace: "1024",
        storageSpaceUnit: "GB",
        transferSpeed: "1600",
        transferSpeedUnit: "MB/s",
        isNVME: false,
      },
    ],
    rentDetail: {
      duration: 24,
      durationUnit: "Hours",
      endAt: "13-2-2022 00:00:00AM",
      price: 5,
      priceUnit: "$ / Hour",
      status: "ACTIVE",
    },
  },
  {
    title: "Pc kuwat RTX 3080 Cocok untuk render",
    ID: "1234567890",
    date: "12-02-2022",
    img: {
      src: "https://www.shutterstock.com/image-photo/gaming-pc-rgb-led-lights-600w-1621672105.jpg",
      alt: "img-1",
    },
    cpu: {
      title: "Intel I5 6600K",
      core: 4,
      thread: 4,
      clockSpeed: 3.9,
    },
    graphical: {
      title: "Nvidia RTX 3080",
      cudeCore: 10240,
      clockSpeed: 3.9,
      memory: 12,
      memoryUnit: "GB",
      memoryType: "GDDR6X",
    },
    storageList: [
      {
        title: "Main Disk C",
        storageSpace: "512",
        storageSpaceUnit: "GB",
        transferSpeed: "3200",
        transferSpeedUnit: "MB/s",
        isNVME: true,
        installedOs: true,
      },
      {
        title: "Storage Disk D",
        storageSpace: "1024",
        storageSpaceUnit: "GB",
        transferSpeed: "1600",
        transferSpeedUnit: "MB/s",
        isNVME: false,
      },
      {
        title: "Storage Disk E",
        storageSpace: "1024",
        storageSpaceUnit: "GB",
        transferSpeed: "1600",
        transferSpeedUnit: "MB/s",
        isNVME: false,
      },
    ],
    rentDetail: {
      duration: 24,
      durationUnit: "Hours",
      endAt: "13-2-2022 00:00:00AM",
      price: 5,
      priceUnit: "$ / Hour",
      status: "ACTIVE",
    },
  },
  {
    title: "Pc kuwat RTX 3080 Cocok untuk render",
    ID: "1234567890",
    date: "12-02-2022",
    img: {
      src: "https://www.shutterstock.com/image-photo/gaming-pc-rgb-led-lights-600w-1621672105.jpg",
      alt: "img-1",
    },
    cpu: {
      title: "Intel I5 6600K",
      core: 4,
      thread: 4,
      clockSpeed: 3.9,
    },
    graphical: {
      title: "Nvidia RTX 3080",
      cudeCore: 10240,
      clockSpeed: 3.9,
      memory: 12,
      memoryUnit: "GB",
      memoryType: "GDDR6X",
    },
    storageList: [
      {
        title: "Main Disk C",
        storageSpace: "512",
        storageSpaceUnit: "GB",
        transferSpeed: "3200",
        transferSpeedUnit: "MB/s",
        isNVME: true,
        installedOs: true,
      },
      {
        title: "Storage Disk D",
        storageSpace: "1024",
        storageSpaceUnit: "GB",
        transferSpeed: "1600",
        transferSpeedUnit: "MB/s",
        isNVME: false,
      },
      {
        title: "Storage Disk E",
        storageSpace: "1024",
        storageSpaceUnit: "GB",
        transferSpeed: "1600",
        transferSpeedUnit: "MB/s",
        isNVME: false,
      },
    ],
    rentDetail: {
      duration: 24,
      durationUnit: "Hours",
      endAt: "13-2-2022 00:00:00AM",
      price: 5,
      priceUnit: "$ / Hour",
      status: "ACTIVE",
    },
  },
];
