export const STORE_INITIAL_VALUE = {
  id: "",
  storeName: "",
  storeCode: "",
  storeDescription: "",
  storePhone: "",
  storeWhatsapp: "",
  storeEmail: "",
  storeProvince: "Pilih Provinsi",
  storeRegency: "Pilih Kota",
  storeDistrict: "Pilih Kecamatan",
  storeVillage: "Pilih Kelurahan",
  storeAddress: "",
  storePostalCode: "",
};
